ISO_3166_CODES_BY_COUNTRY = {
    "Afeganistão": "AFG",
    "Ilhas Åland": "ALA",
    "Albânia": "ALB",
    "Argélia": "DZA",
    "Samoa Americana": "ASM",
    "Andorra": "AND",
    "Angola": "AGO",
    "Anguilla": "AIA",
    "Antártida": "ATA",
    "Antígua e Barbuda": "ATG",
    "Argentina": "ARG",
    "Armênia": "ARM",
    "Aruba": "ABW",
    "Austrália": "AUS",
    "Áustria": "AUT",
    "Azerbaijão": "AZE",
    "Bahamas": "BHS",
    "Bahrein": "BHR",
    "Bangladesh": "BGD",
    "Barbados": "BRB",
    "Bielorrússia": "BLR",
    "Bélgica": "BEL",
    "Belize": "BLZ",
    "Benin": "BEN",
    "Bermudas": "BMU",
    "Butão": "BTN",
    "Bolívia": "BOL",
    "Países Baixos Caribenhos": "BES",
    "Bósnia e Herzegovina": "BIH",
    "Botswana": "BWA",
    "Ilha Bouvet": "BVT",
    "Brasil": "BRA",
    "Território do Oceano Índico Britânico": "IOT",
    "Brunei": "BRN",
    "Bulgária": "BGR",
    "Burkina Faso": "BFA",
    "Burundi": "BDI",
    "Cabo Verde": "CPV",
    "Cambodja": "KHM",
    "Camarões": "CMR",
    "Canadá": "CAN",
    "Ilhas Cayman": "CYM",
    "República Centro-Africana": "CAF",
    "Chade": "TCD",
    "Chile": "CHL",
    "China": "CHN",
    "Ilha Christmas": "CXR",
    "Ilhas Cocos": "CCK",
    "Colômbia": "COL",
    "Comores": "COM",
    "Congo": "COG",
    "República Democrática do Congo": "COD",
    "Ilhas Cook": "COK",
    "Costa Rica": "CRI",
    "Costa do Marfim": "CIV",
    "Croácia": "HRV",
    "Cuba": "CUB",
    "Curaçao": "CUW",
    "Chipre": "CYP",
    "República Tchéquia": "CZE",
    "Dinamarca": "DNK",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "República Dominicana": "DOM",
    "Equador": "ECU",
    "Egito": "EGY",
    "El Salvador": "SLV",
    "Guiné Equatorial": "GNQ",
    "Eritrea": "ERI",
    "Estônia": "EST",
    "Suazilândia": "SWZ",
    "Etiópia": "ETH",
    "Ilhas Malvinas": "FLK",
    "Ilhas Faroé": "FRO",
    "Fiji": "FJI",
    "Finlândia": "FIN",
    "França": "FRA",
    "Guiana Francesa": "GUF",
    "Polinésia Francesa": "PYF",
    "Terras Austrais e Antárticas Francesas": "ATF",
    "Gabão": "GAB",
    "Gâmbia": "GMB",
    "Geórgia": "GEO",
    "Alemanha": "DEU",
    "Gana": "GHA",
    "Gibraltar": "GIB",
    "Grécia": "GRC",
    "Groenlândia": "GRL",
    "Granada": "GRD",
    "Guadeloupe": "GLP",
    "Guadalupe": "GUM",
    "Guatemala": "GTM",
    "Guernsey": "GGY",
    "Guiné": "GIN",
    "Guiné-Bissau": "GNB",
    "Guiana": "GUY",
    "Haiti": "HTI",
    "Ilha Heard e Ilhas McDonald": "HMD",
    "Vaticano": "VAT",
    "Honduras": "HND",
    "Hong Kong": "HKG",
    "Hungria": "HUN",
    "Islândia": "ISL",
    "Índia": "IND",
    "Indonésia": "IDN",
    "Irã": "IRN",
    "Iraque": "IRQ",
    "Irlanda": "IRL",
    "Ilha de Man": "IMN",
    "Israel": "ISR",
    "Itália": "ITA",
    "Jamaica": "JAM",
    "Japão": "JPN",
    "Jersey": "JEY",
    "Jordânia": "JOR",
    "Cazaquistão": "KAZ",
    "Quênia": "KEN",
    "Quiribati": "KIR",
    "Coreia do Norte": "PRK",
    "Coreia do Sul": "KOR",
    "Kuwait": "KWT",
    "Quirguistão": "KGZ",
    "Laos": "LAO",
    "Letônia": "LVA",
    "Líbano": "LBN",
    "Lesoto": "LSO",
    "Libéria": "LBR",
    "Líbia": "LBY",
    "Liechtenstein": "LIE",
    "Lituânia": "LTU",
    "Luxemburgo": "LUX",
    "Macau": "MAC",
    "Madagascar": "MDG",
    "Malawi": "MWI",
    "Malásia": "MYS",
    "Maldivas": "MDV",
    "Mali": "MLI",
    "Malta": "MLT",
    "Ilhas Marshall": "MHL",
    "Martinica": "MTQ",
    "Mauritânia": "MRT",
    "Maurícia": "MUS",
    "Mayotte": "MYT",
    "México": "MEX",
    "Estados Federados da Micronésia": "FSM",
    "Moldávia": "MDA",
    "Mônaco": "MCO",
    "Mongólia": "MNG",
    "Montenegro": "MNE",
    "Montserrat": "MSR",
    "Marrocos": "MAR",
    "Moçambique": "MOZ",
    "Myanmar": "MMR",
    "Namíbia": "NAM",
    "Nauru": "NRU",
    "Nepal": "NPL",
    "Holanda": "NLD",
    "Nova Caledônia": "NCL",
    "Nova Zelândia": "NZL",
    "Nicarágua": "NIC",
    "Níger": "NER",
    "Nigéria": "NGA",
    "Niue": "NIU",
    "Ilha Norfolk": "NFK",
    "Macedônia do Norte": "MKD",
    "Ilhas Marianas Setentrionais": "MNP",
    "Noruega": "NOR",
    "Omã": "OMN",
    "Paquistão": "PAK",
    "Palau": "PLW",
    "Palestina": "PSE",
    "Panamá": "PAN",
    "Papua-Nova Guiné": "PNG",
    "Paraguai": "PRY",
    "Peru": "PER",
    "Filipinas": "PHL",
    "Ilhas Pitcairn": "PCN",
    "Polônia": "POL",
    "Portugal": "PRT",
    "Porto Rico": "PRI",
    "Qatar": "QAT",
    "Réunion": "REU",
    "Romênia": "ROU",
    "Rússia": "RUS",
    "Rwanda": "RWA",
    "São Bartolomeu": "BLM",
    "Santa Helena": "SHN",
    "Saint Kitts e Nevis": "KNA",
    "Santa Lúcia": "LCA",
    "Saint Martin (França)": "MAF",
    "Saint Pierre e Miquelon": "SPM",
    "São Vicente e Granadinas": "VCT",
    "Samoa": "WSM",
    "San Marino": "SMR",
    "São Tomé e Príncipe": "STP",
    "Arábia Saudita": "SAU",
    "Senegal": "SEN",
    "Sérvia": "SRB",
    "Seychelles": "SYC",
    "Serra Leoa": "SLE",
    "Singapura": "SGP",
    "São Martinho": "SXM",
    "Eslováquia": "SVK",
    "Eslovênia": "SVN",
    "Ilhas Salomão": "SLB",
    "Somália": "SOM",
    "África do Sul": "ZAF",
    "Ilhas Geórgia do Sul e Sandwich do Sul": "SGS",
    "Sudão do Sul": "SSD",
    "Espanha": "ESP",
    "Sri Lanka": "LKA",
    "Sudão": "SDN",
    "Suriname": "SUR",
    "Svalbard e Jan Mayen": "SJM",
    "Suécia": "SWE",
    "Suíça": "CHE",
    "Síria": "SYR",
    "Taiwan": "TWN",
    "Tajiquistão": "TJK",
    "Tanzânia": "TZA",
    "Tailândia": "THA",
    "Timor-Leste": "TLS",
    "Togo": "TGO",
    "Toquelau": "TKL",
    "Tonga": "TON",
    "Trinidade e Tobago": "TTO",
    "Tunísia": "TUN",
    "Turquia": "TUR",
    "Turquemenistão": "TKM",
    "Ilhas Turcas e Caicos": "TCA",
    "Tuvalu": "TUV",
    "Uganda": "UGA",
    "Ucrânia": "UKR",
    "Emirados Árabes": "ARE",
    "Reino Unido": "GBR",
    "Estados Unidos": "USA",
    "Ilhas Menores Distantes dos Estados Unidos": "UMI",
    "Uruguai": "URY",
    "Uzbequistão": "UZB",
    "Vanuatu": "VUT",
    "Venezuela": "VEN",
    "Vietnã": "VNM",
    "Ilhas Virgens Britânicas": "VGB",
    "Ilhas Virgens Americanas": "VIR",
    "Wallis e Futuna": "WLF",
    "Saara Ocidental": "ESH",
    "Iémen": "YEM",
    "Zâmbia": "ZMB",
    "Zimbabwe": "ZWE",
}
